const INTL_FETCH_TRANSLATION_START = 'INTL/FETCH_TRANSLATION_START';
const INTL_FETCH_TRANSLATION_SUCCESS = 'INTL/FETCH_TRANSLATION_SUCCESS';
const INTL_FETCH_TRANSLATION_FAILED = 'INTL/FETCH_TRANSLATION_FAILED';

const types = {
  INTL_FETCH_TRANSLATION_START,
  INTL_FETCH_TRANSLATION_SUCCESS,
  INTL_FETCH_TRANSLATION_FAILED
};

export default types;
