language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build
  - yarn test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: e09dda32ec3d1f55eae5be1134a5fbba2547f6e7
  keep-history: true
  local-dir: build
  target-branch: master
  verbose: true
  on:
    branch: src
