language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build
  - yarn test

after_script:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN yarn coveralls

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  target-branch: master
  verbose: true
  on:
    branch: src
